# Generated by Django 5.0.6 on 2024-12-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalsolutions',
            name='uom',
            field=models.CharField(max_length=300),
        ),
    ]
